dashpay/tenderdash

- third_party/bls-signatures/build.sh
- third_party/bls-signatures/install.sh
> build: BLS scripts - Improve build.sh, Fix install.sh

- .github/workflows/docker.yml
- DOCKER/Dockerfile
- DOCKER/Dockerfile.build_c-amazonlinux
- DOCKER/docker-entrypoint.sh
- Makefile
- docker-compose.yml
- test/e2e/Makefile
- test/e2e/README.md
- test/e2e/app/main.go
- test/e2e/docker/Dockerfile
- test/e2e/docker/entrypoint
- test/e2e/docker/entrypoint-builtin
- test/e2e/docker/entrypoint-maverick
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/cleanup.go
- test/e2e/runner/setup.go
- tools/tm-signer-harness/Makefile
Note: I guess it's a good idea to create the mail address `tenderdash@dash.org` introduced in 1543835. @shumkov Can you take care of this?
> build: Dashify some files

- .github/workflows/docker.yml
- DOCKER/Dockerfile
- Makefile
> build: fix docker image and docker.yml workflow

- config/toml.go
- crypto/bls12381/bls12381_test.go
- light/helpers_test.go
- types/block.go
- types/block_test.go
- types/params_test.go
All stuff required to let the linter pass.
> linter: fix some bls-related linter issues

- .github/workflows/coverage.yml
> build: fix coverage.yml, bump go version, install BLS, drop an invalid character

- .github/workflows/tests.yml
`tests.yml` should now pass with this. However, please take a look into the logs.. last time i checked them there were some errors in there... might be expected errors or so, didn't investigate a lot yet just overflew it. Will link it here as soon as it run through.
> build: fix test.yml, bump go version, install BLS, fix job names

- .github/workflows/e2e.yml
- test/e2e/docker/Dockerfile
- test/e2e/pkg/testnet.go
This PR makes e2e github action passing.
> ci: e2e fixes - docker image, e2e.yml BLS library, default KeyType

- test/e2e/Makefile
Remove hardcoded path from docker volume
> Fix e2e makefile

- test/maverick/consensus/reactor.go
- test/maverick/consensus/replay.go
- test/maverick/consensus/replay_file.go
- test/maverick/consensus/state.go
- test/maverick/node/node.go
Update maverick code with the most recent changes in consensus and resolve compile issues
> fix: maverick compile issues

- test/maverick/consensus/reactor.go
- test/maverick/consensus/replay.go
- test/maverick/consensus/replay_file.go
- test/maverick/consensus/state.go
- test/maverick/node/node.go
Reverts dashevo/tenderdash#104
> Revert "fix: maverick compile issues"

- test/maverick/consensus/state.go
- test/maverick/node/node.go
_Please add a description of the changes that this PR introduces and the files that
are the most critical to review._ 
Closes: #XXX
> Fix maverick compile issue

- test/e2e/app/main.go
- test/e2e/pkg/mockcoreserver/core_server.go
- test/e2e/pkg/mockcoreserver/methods.go
- test/e2e/pkg/mockcoreserver/server_test.go
_Please add a description of the changes that this PR introduces and the files that
are the most critical to review._ 
Closes: #XXX
> NO-TICKET Add ping method to CoreMockServer

- light/provider/http/http.go
- test/e2e/runner/rpc.go
- types/validator.go
> small fix for validator proto pub keys

- .github/workflows/docker.yml
Image wasn't pushed to docker hub after build
- Set `push: true`
In CI
None
> fix: image isn't pushed after build

- rpc/core/mempool.go
- rpc/core/types/responses.go
Added info field to ResultBroadcastTx response structure
Added info field with arbitrary data to ResultBroadcastTx
> feat(rpc): info field with arbitrary data to ResultBroadcastTx

- .github/workflows/coverage.yml
- consensus/core_chainlock_test.go
Current CI process fails to build for amd64 and arm
Split up the build process for both architectures
Changed the CC and CXX env variables
Deploy and it built successfully
> fix: amd64 build and arm build ci

- consensus/reactor.go
- consensus/state_test.go
- test/e2e/pkg/mockcoreserver/server_test.go
Created variable copies and moved go routines around to prevent data races
https://dashpay.atlassian.net/jira/software/projects/TD/boards/119?selectedIssue=TD-25
Ran the tests locally, they passed
> fix: test (00) and test (03) in Test Coverage - CI

- config/config.go
- test/app/test.sh
Test_apps CI [simulates communication between core and abci application]
Using init-single when setting up the tenderdash node
Changed the appHashSize to defaultAppHashSize from smallAppHashSize
CI Test passes.
> test: fix test_apps tests

- consensus/core_chainlock_test.go
Fixed data race issue in some core chain lock test
Updated state access to be concurrency safe.
Tested locally, and CI passes
> test: fix core chainlock data race

- privval/dash_core_signer_client.go
DashCoreSignerClient is losing error details when something goes wrong. 
Fixed order of processing errors in DashCoreSignerClient
GitHub pipelines
None
> fix(privval): improved error handling  in DashCoreSignerClient

- consensus/wal_test.go
Added test to ensure that commit state ID is written correctly to WAL
Added 1 unit test
started the test
n/a
> test(consensus): ensure commit stateid in wal is correct

- crypto/bls12381/bench_test.go
- crypto/bls12381/bls12381_test.go
- internal/blocksync/v0/reactor_test.go
- internal/blocksync/v2/reactor.go
- internal/consensus/state.go
- internal/evidence/pool_test.go
- internal/evidence/reactor_test.go
- internal/inspect/inspect_test.go
- internal/p2p/conn/connection.go
- internal/p2p/peer_set_test.go
- internal/p2p/shim_test.go
- internal/rpc/core/blocks.go
- internal/rpc/core/blocks_test.go
- internal/state/export_test.go
- internal/state/helpers_test.go
- internal/state/rollback.go
- internal/state/rollback_test.go
- internal/state/store_test.go
- internal/statesync/block_queue_test.go
- internal/statesync/reactor_test.go
- internal/statesync/stateprovider.go
- internal/test/factory/commit.go
- libs/log/logger.go
- types/validation.go
some fixes to be able to compile the add
> fix: some fixes to be able to compile the add

- light/client_benchmark_test.go
- light/helpers_test.go
- light/light_test.go
> Light client v35 merge fixes

- dash/quorum/validator_conn_executor.go
Fixed: Validator disconnected outside of Validator Set was not found in the Switch but never removed from ValidatorConnExecutor.connectedValidators.
Improved error handling
1. Unit tests
2. E2E tests
3. Manual review of devnet
None
> fix: don't disconnect already disconnected validators

- .github/workflows/coverage.yml
> fix git workflow

- internal/blocksync/v0/reactor.go
- internal/blocksync/v2/processor_context.go
- internal/blocksync/v2/reactor.go
- internal/blocksync/v2/reactor_test.go
- internal/consensus/replay.go
- internal/consensus/replay_test.go
- internal/consensus/state.go
- internal/p2p/switch_test.go
- internal/p2p/test_util.go
- internal/state/execution.go
- internal/state/execution_test.go
- internal/state/export_test.go
- internal/state/helpers_test.go
- internal/state/state_test.go
- internal/state/validation_test.go
- node/node.go
- node/setup.go
- types/node_info.go
- types/validator_set.go
Since slice is already pointer it doesn't make sense to use pointer of slice
Changed a type of proTxHash from slice pointer to slice
Using unit tests
> refactor: change node's proTxHash on slice from pointer of slice

- dash/quorum/mock/dash_dialer.go
- internal/p2p/dash_dialer.go
- internal/p2p/peermanager.go
Since using a mutex from an external component is not recommended, the corresponding code in routerDashDialer has been moved to PeerManger
* move the code that read and change the state of PeerManager form routerDashDialer in PeerManger itself
* fix typo in docs of DashDialer implementations
unit-test
n/a
> refactor: some minor changes in validate-conn-executor and routerDashDialer

- libs/bits/bit_array.go
Detected potential deadlock in an implementation of bit-array component
Refactored `bit-array` component to eliminate deadlock issue and make a code more unambiguous 
Unit-test
N/A
> refactor(bits-array): fix potential deadlock in bit_array.go

- go.mod
- go.sum
Support a new version of dashevo/dashd-go
Updated module `dashevo/dashd-go` to `v0.23.4` version
used unit-test
> Update dashevo dashd go

- internal/state/state_test.go
Noticed a few missed required things for:
* updating validator-set via single transaction, rather than multiple
* check the whole validator-set, rather than only count of validators
* redundant code
* update validator-set with a single tx
* added an assert function where checking a whole validator-set with threshold public key and proTxHashes of all members
* deleted unused/redundant code
unit-test
no
> refactor: small improvement in test four add four minus one genesis validators

- .github/workflows/proto.yml
- Makefile
- README.md
- proto/tendermint/types/types.proto
Provide base branch to make proto-check-breakage from outside.
* updated Makefile
* updated github workflow
* minor update of README
Using Github actions
n/a
> build(ci): provide base branch to make as variable

- .github/workflows/lint.yaml
Also specify Go toolchain version in actions (now required).
(cherry picked from commit 14461339f43029e1cfedf799fa8a60ffcf1f5b69)
> build(ci): Update golangci-lint-action and golang-ci versions (backport from 0.8)

- .github/workflows/docker.yml
- DOCKER/Dockerfile
- buildx was using an unnecessary cache hack
- native arm build of the Dockerfile was failing with:
```
#0 19.12 /go/pkg/mod/github.com/oasisprotocol/curve25519-voi@v0.0.0-20220328075252-7dd334e3daae/primitives/ed25519/batch_verify.go:38:2: //go:build comment without // +build comment
#0 19.12 /go/pkg/mod/github.com/oasisprotocol/curve25519-voi@v0.0.0-20220328075252-7dd334e3daae/curve/edwards.go:38:2: //go:build comment without // +build comment
#0 19.12 /go/pkg/mod/github.com/oasisprotocol/curve25519-voi@v0.0.0-20220328075252-7dd334e3daae/curve/constants.go:34:8: //go:build comment without // +build comment
#0 19.12 /go/pkg/mod/github.com/oasisprotocol/curve25519-voi@v0.0.0-20220328075252-7dd334e3daae/primitives/merlin/merlin.go:42:2: //go:build comment without // +build comment
#0 19.12 …
```
> ci: fixes for arm builds

- .github/workflows/lint.yaml
- CHANGELOG.md
- consensus/replay.go
- consensus/state.go
- consensus/state_test.go
- consensus/wal_iter.go
- consensus/wal_iter_test.go
- crypto/xchacha20poly1305/xchachapoly_test.go
- p2p/conn/connection.go
- scripts/release/cliff.toml
- scripts/release/release.sh
- types/block.go
- types/block_test.go
- version/version.go
> chore(release): update changelog and bump version to 0.7.1

- internal/consensus/peer_state.go
- internal/consensus/reactor.go
Detected data race:
```
WARNING: DATA RACE
Write at 0x00c0002febe0 by goroutine 235:
github.com/tendermint/tendermint/internal/consensus.(*PeerState).SetProTxHash()
/home/runner/work/tenderdash/tenderdash/internal/consensus/peer_state.go:394 +0x[152](https://github.com/dashevo/tenderdash/runs/5972325446?check_suite_focus=true#step:6:152)
github.com/tendermint/tendermint/internal/consensus.(*Reactor).peerUp()
/home/runner/work/tenderdash/tenderdash/internal/consensus/reactor.go:1053 +0x329
github.com/tendermint/tendermint/internal/consensus.(*Reactor).processPeerUpdate()
/home/runner/work/tenderdash/tenderdash/internal/consensus/reactor.go:1031 +0x3c4
github.com/tendermint/tendermint/internal/consensus.(*Reactor).processPeerUpdates() …
```
> fix: use thread-safely way to get pro-tx-hash from peer-state

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.2

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.3

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.4

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.6

- types/validator_set.go
If a genesis validator list is empty, then tenderdash fails with a panic on a handshake
Bug was fixed
Unit-Test
No
> fix: check a receiver of ValidatorSet on nil

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.7

- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.8

- DOCKER/Dockerfile
Downgraded alpine image version, due to BLS library with the latest alpine doesn't compile
Downgraded alpine image version
Built image locally
N/A
> chore: update alpine image version

- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.9

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.8.0-dev.10

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.9.0-dev.1

- internal/blocksync/reactor.go
- internal/consensus/types/height_vote_set.go
- types/vote_set.go
Fixed some go lint issues
N/A
N/A
> chore: remove stateID from VoteSet and HeightVoteSet

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.10.0-dev.1

- internal/state/validation.go
The logic of `validateBlockTime` function has backported wrong
Revert code to a correct one
Test
N/A
> chore: revert `validateBlockTime`

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.10.0-dev.2

- cmd/tenderdash/commands/run_node.go
- config/config.go
- config/toml.go
Need to remove unused PexReactor field from p2p config
The field was removed
> refactor(config): remove PexReactor parameter from p2p config

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.10.0-dev.3

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.10.0-dev.4

- config/config.go
- config/toml.go
- internal/consensus/common_test.go
- internal/consensus/replay.go
- internal/consensus/replay_test.go
- internal/consensus/state.go
- internal/consensus/wal_generator_test.go
- internal/consensus/wal_iter.go
- internal/consensus/wal_iter_test.go
Based on the [report](https://dashpay.atlassian.net/browse/TD-84), the mechanism of skipping rounds to the last works unstable. Need to fix and improve the process execution WAL messages.
* Refactor the current implementation of skipping rounds to the last
* Add configuration parameter to enable this feature
unit and e2e tests
N/A
> fix(wal): improve wal replay mechanism

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.11.0-dev.1

- .github/workflows/build.yml
- DOCKER/Dockerfile
- Makefile
- third_party/bls-signatures/build.sh
- third_party/bls-signatures/install.sh
CGO paths to BLS deps are incorrect
Fix CGO paths in Makefile
N/A
N/A
> build: CGO paths to BLS deps are incorrect

- .github/actions/bls/action.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- Makefile
- go.mod
- go.sum
- test/Makefile
- test/e2e/Makefile
- test/e2e/docker/Dockerfile
- test/e2e/generator/generate.go
- test/e2e/networks/ci.toml
- test/e2e/networks/dashcore.toml
- test/e2e/networks/island.toml
- test/e2e/networks/rotate.toml
- test/e2e/pkg/testnet.go
- third_party/bls-signatures/build.sh
Need to update BLS revision, due to upstream has moved forward since the current revision.
* Updated revision to 1.2.5 ([85b7e61](https://github.com/dashpay/bls-signatures/commit/85b7e61b5573dff356dfba3d02f2e10468aadb57))
* Updated BLS linking and its dependencies
* Fix E2E Dockerfile (RocksDB is not supported anymore)
Unit / E2E tests
N/A
> chore: update bls library

- internal/statesync/dispatcher.go
- internal/statesync/dispatcher_test.go
- internal/statesync/reactor.go
Light-block dispatcher writes logs using `fmt.Printf` calls
Use logger for writing logs
Unit and E2E tests
N/A
> refactor: use logger for log printing

- internal/consensus/helper_test.go
- internal/consensus/replay_test.go
- internal/consensus/state.go
Test `TestWALRoundsSkipper` is flaky, need to fix this unstable behaviour
* Changed assertions from strict equality on a bit softer (greater or equal)
* Added ability to stop consensus state using stop function
Unit and E2E tests
N/A
> fix: improve flaky TestWALRoundsSkipper

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.11.0-dev.2

- .github/workflows/docker.yml
Docker build process is broken in v0.11-dev, the issue was already fixed PR-580, and presented in v0.10-dev
Backported the latest changes from v0.10-dev into v0.11-dev
Tests
N/A
> backport: catch up the latest changes from v0.10 to v0.11

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.11.0-dev.3

- go.mod
- go.sum
Need to update dashd-go version to the latest
Bump up dashd-go version from v0.23.4 to v0.23.6
Tests
N/A
> chore: bump up dashd-go version to v0.23.6

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.10.0-dev.10

- go.mod
- go.sum
Need to catch up the recent changes from v0.10-dev
Backported the changes from v0.10-dev to v0.11-dev
N/A
N/A
> backport: catch up the recent changes from v0.10 to v0.11

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.11.0-dev.4

- .github/workflows/docker.yml
- internal/p2p/peermanager.go
- internal/p2p/pex/reactor_test.go
To switch on v0.11-dev as default, need to catch up the recent changes from v0.10-dev
Backported the recent chnages from v0.10-dev
Unit and E2E tests
N/A
> backport: v0.10 to v0.11

- Makefile
Need to add quote to CGO variables in Makefile
Added quote to CGO variables in Makefile
N/A
N/A
> chore: add quote to CGO variables in Makefile

- internal/consensus/gossip_peer_worker.go
Sometimes e2e tests are failed because of missed `logger` in `consensus.blockRepository`
Added logger to `consensus.blockRepository`
Unit/E2E tests
N/A
> fix: add logger to consensus.blockRepository

- rpc/jsonrpc/client/http_json_client.go
- rpc/jsonrpc/client/http_json_client_test.go
- rpc/jsonrpc/client/integration_test.go
- rpc/jsonrpc/client/ws_client.go
Test `TestMakeHTTPDialerURL` has stopped working
* The test `TestMakeHTTPDialerURL` has fixed
* Renamed on `TestDialParamsFromURL`
Unit-test
N/A
> test: fix TestMakeHTTPDialerURL

- rpc/jsonrpc/client/http_json_client.go
- rpc/jsonrpc/client/http_json_client_test.go
- rpc/jsonrpc/client/integration_test.go
- rpc/jsonrpc/client/ws_client.go
Need to  catch up the recent commits from `v0.11-dev` into `v0.12-dev`
Backported the recent commit(s) from `v0.11-dev` into `v0.12-dev`
Unit tests
N/A
> backport: catch up the recent commits from v0.11-dev into v0.12-dev

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.12.0-dev.1

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.11.1

- dash/llmq/llmq.go
LLMQType_25_67 has wrong minimal members threshold specified in quorum params
- Changed threshold param to correct one - 17
None
Previous blockchain data won't be valid
> fix!: invalid threshold for LLMQType_25_67

- CHANGELOG.md
- dash/llmq/llmq.go
- version/version.go
> chore(release): update changelog and bump version to 0.11.2

- CHANGELOG.md
- cmd/tenderdash/main.go
- config/config.go
- config/toml.go
- libs/log/default.go
Catch up the changes from v0.11 to v0.12
Backported the recent changes from v0.11-dev
Unit / E2E tests
N/A
> backport: catch up the changes from v0.11 to v0.12

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.13.0-dev.2

- CHANGELOG.md
- cmd/tenderdash/commands/root.go
- cmd/tenderdash/main.go
- libs/log/default.go
- libs/log/logger.go
- version/version.go
> chore(release): update changelog and bump version to 0.13.2

- Makefile
On mac, GMP wasn't easily being linked, this is now solved.
> fix: issue with GMP not properly being linked on mac

- CHANGELOG.md
- libs/ds/ordered_map.go
- libs/ds/ordered_map_test.go
- version/version.go
> fix: ordered map race condition

- CHANGELOG.md
- internal/rpc/core/events.go
- libs/ds/ordered_map.go
- libs/ds/ordered_map_test.go
- rpc/jsonrpc/server/ws_handler.go
- version/version.go
> chore(release): update changelog and bump version to 0.13.4

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.14.0-dev.1

- libs/ds/ordered_map.go
- libs/ds/ordered_map_test.go
> fix: panic in ordered_map Key()

- DOCKER/Dockerfile
- Makefile
- README.md
- docs/introduction/install.md
- test/e2e/docker/Dockerfile
- third_party/bls-signatures/build.sh
- third_party/bls-signatures/install.sh
* fixes #723 
* fixes #724 
* fixes #725 
1. Updated documentation
2. Removed sudo and fixed default install location
3. Disabled Python bindings in BLS
4. Updated Dockerfiles to remove Python dependency
In local Ubuntu VM
None
> build: simplify build process

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.14.0-dev.4

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.14.0-dev.5

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.14.0-dev.6

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.14.0-dev.7

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 0.14.0-dev.8

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 1.0.0-dev.2

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 1.1.0-dev.1

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 1.1.0-dev.2

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 1.2.0-dev.2

- CHANGELOG.md
- version/version.go
> chore(release): update changelog and bump version to 1.2.0-dev.3

- .github/CODEOWNERS
@shumkov is no longer a code owner
Removed from CODEOWNERS
N/A
N/A
> chore: remove shumkov from CODEOWNERS

- .github/workflows/docker.yml
- CHANGELOG.md
- DOCKER/Dockerfile
- version/version.go
> chore(release): update changelog and bump version to 1.5.1
