p2p/node_info_test.go
p2p/peer_set_test.go

Use ed25519 keys as node_info_key in tests

crypto: switched node keys back to edwards

---

crypto/bls12381/bls12381.go
crypto/crypto.go
crypto/ed25519/ed25519.go
crypto/secp256k1/secp256k1.go
crypto/sr25519/privkey.go
crypto/sr25519/pubkey.go
p2p/conn/secret_connection_test.go
state/execution.go
types/protobuf_test.go

This PR revokes renaming of `Type()` to `TypeIdentifier()` which happened
with the BLS integration. There `crypto.KeyType` was introduced which is
used as return value of `Type()` after the integration. This leads to
`e2e.yml` failure due to toml parser failing down the road because it gets a
`crypto.KeyType` (int64) 
https://github.com/dashevo/tenderdash/blob/26493bbbd86d3a2e9b982d8c9f45323e81c2aea1/test/e2e/runner/setup.go#L320
where it expects a `string`
https://github.com/dashevo/tenderdash/blob/26493bbbd86d3a2e9b982d8c9f45323e81c2aea1/test/e2e/app/config.go#L25
Just renaming it in the following way fixes the issue and should avoid
running into similar issues related to `Type()` usage potentially coming
from later upstream backports:
`TypeIdentifier() string` => `Type() string` …

crypto|p2p|state|types: Rename Pub/PrivKey's TypeIdentifier() and Type()

---

.github/workflows/lint.yaml

Requires #13  and #14 to pass `lint.yml`

ci: install BLS library in lint.yml and bump its go version

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR updates the GitHub PR and Issue templates so they conform with the templates we use in other repos. Some useful parts of the original Tendermint templates have been included as well.
Closes: #XXX

docs: update github issue and pr templates

---

.github/workflows/docker.yml
Makefile
scripts/dist.sh

ARM builds were previously failing with:
```
#18 ERROR: executor failed running [/bin/sh -c make build-linux]: exit code: 2
------
> [linux/arm64 builder 6/6] RUN make build-linux:
------
Dockerfile:12
--------------------
10 |     
11 |     RUN make install-bls
12 | >>> RUN make build-linux
13 |     
14 |     FROM alpine:3.9
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c make build-linux]: exit code: 2
Error: buildx failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c make build-linux]: exit code: 2
```
Credit to Nathan for finding these fixes!!
- Enable `arm64` arch build target
- Do not explicitly target `amd64` during `make build-linux`
- Enable arm64 arch in CI
On …

ci: fix arm64 build

---

.github/workflows/lint.yaml

v1.41 of golangci-lint catches more linting errors e.g appendAssign in gocritic

ci: upgraded golangci-lint from v1.38 to v1.41

---

config/config.go
config/toml.go
consensus/state.go
state/execution.go
state/validation.go
test/maverick/consensus/misbehavior.go

In order to be able to change a proposed block time window, the hardcoded value was moved in a config file
the validator uses the value from the configuration to create the window borders
* Define `proposed_block_time_window` parameter in a configuration and map this parameter to `ProposedBlockTimeWindow` in a config structure
It is already covered by unit tests
Updated the signature of `ValidateBlockTime` method, added `ProposedBlockTimeWindow` as first argument

feat: add ProposedBlockTimeWindow in a config

---

light/client.go
test/e2e/docker/Dockerfile

Inside state sync AppHash lookup, we try to download light block for future heights (`height+2`, `height+2`). In some scenarios, this fails (correctly), because this block does not exist yet.
In case of error, error handling in `lightBlockFromPrimaryAtHeight()` assumes the primary is "broken", and tries to find a new primary (`findNewPrimary()`) that will work correctly. Unfortunately, `findNewPrimary()` was trying to retrieve most recent block,
effectively missing the fact that error happened due to height that does not exist yet (eg.  `height+2`).
In effect, `findNewPrimary()` returned most recent block, which in turn was sent to AppHash() and was NOT what was expected.
findNewPrimary() now accepts additional argument, `height`, and tries to find a primary which provides that height. …

fix: state sync hangs when trying to retrieve AppHash

---

test/e2e/README.md
test/e2e/docker/Dockerfile
test/e2e/docker/entrypoint-builtin
test/e2e/runner/setup.go

We need a way to debug Tendermint running inside Docker containers as part of end-to-end (e2e) tests.
See [docs](https://github.com/dashevo/tenderdash/blob/lklimek/e2e-delve/test/e2e/README.md#delve-debugger) for details.
1. Installed delve (dlv) inside e2e Docker container
2. If environment variable DEBUG is set, run tenderdash app inside dlv session
Tested locally using MS Visual Studio Code, with `DEBUG=1 go run ./runner -f networks/dashcore.toml`

build: make debugging of e2e docker apps easier

---

libs/cmap/cmap.go
libs/cmap/cmap_test.go
p2p/pex/pex_reactor.go
p2p/switch.go

There is a potential race condition in [p2p.Reactor.RequestAddrs()](https://github.com/dashevo/tenderdash/blob/13e5ec3dda71d0cf422c1175ebf2d4a2b54b28e0/p2p/pex/pex_reactor.go#L346-L350) and [p2p.Switch.reconnectToPeer()](https://github.com/dashevo/tenderdash/blob/HEAD/p2p/switch.go#L384-L387).
```go
if r.requestsSent.Has(id) {
return
}
r.requestsSent.Set(id, struct{}{})
```
If two goroutines enter these functions at the same time, they both can pass the `Has()` check (as it's not set yet), and then, both execute the Set() operation in random order, resulting in a non-deterministic behavior.
Implemented CMap.GetOrSet(), inspired by sync.Map.LoadOrStore(), that checks if value exists, and if not - sets it in an atomic way (eg. within one locking operation).
Run unit tests locally
None
**For …

backport p2p fix: potential race condition in p2p reactor and switch

---

abci/example/kvstore/persistent_kvstore.go

in order to avoid any risks of race conditions, we have to copy validator-set-update rather than using the pointer to this field at PersistentKVStoreApplication, 'cause it leads to a race condition
Provided a copy of validator-set-update in ResponseEndBlock rather than a pointer on this field at PersistentKVStoreApplication
Locally using TestBlockEvents unit-test, that is reported us about this
Nothing

fix: avoid potential race conditions in PersistentKVStoreApplication

---

Makefile
test/e2e/README.md
test/e2e/docker/Dockerfile

Ability to extract and analyze core dumps.
1. e2e tests build with `nostrip` option
2. e2e tests run with `GOTRACEBACK=crash`
3. for `nostrip` builds, `-gcflags=all="-N -l"` are added
4. docs
run locally and used to debug issues
none

e2e: Ability to extract and analyze core dumps

---

p2p/pex/pex_reactor.go

Improved the fix for "orphaned" seeds (PR #198)
Seed will retry the initial connection to other seeds random interval of 0..5 seconds, until at least one connection is successful or a limit of 12 retries is exhausted.
Run e2e tests locally
none

fix(pex): ensure seed at least once connects to another seed

---

.github/workflows/e2e.yml

update github e2e hooks to support dashcore testnet instead of ci.toml
update the hook into .github/e2e.yml
e2e test must pass in github CI
none

fix: update github e2e hooks to support dashcore testnet

---

.github/dependabot.yml
.github/workflows/coverage.yml

* dependabot is running on /docs, which we don't maintain atm
* diff coverage is not calculated correctly
* disabled dependabot on /docs
* updated dependabot reviewers
* enabled coverage testing on v0.*-dev
To be tested after merge, no way to test it locally
none

build: github workflows: fix dependabot and code coverage

---

abci/example/kvstore/persistent_kvstore.go
consensus/common_test.go
consensus/replay_file.go
consensus/replay_test.go
consensus/wal_generator.go
node/node.go
node/node_test.go
proxy/client.go
rpc/client/main_test.go
test/maverick/consensus/replay_file.go
test/maverick/node/node.go

Persistent KV store database is not correctly closed at the end of unit test.
This causes, for example, the following command to fail:
```bash
go test ./consensus/ -run TestReactorValidatorSetChanges -race -count 2
```
Backport https://github.com/tendermint/tendermint/pull/6304 and https://github.com/tendermint/tendermint/pull/6311
1.  `go test ./consensus/ -run TestReactorValidatorSetChanges -race -count 2` succeeds
2. Passed tests from ./consensus and ./abci
none

backport(test): persistent KV store DB not closed correctly

---

.github/workflows/e2e.yml
go.sum

e2e run serialized (what delays execution) and time out.
Copied the job to run in parallel.
Observed github results of job run
N/A

build(e2e): run e2e tests in parallel

---

dash/quorum/selectpeers/dip6.go
dash/quorum/selectpeers/dip6_test.go
dash/quorum/validator_conn_executor_test.go

If we have less than 5 validators in the validator set, we connect to all other validators.
Previously, we didn't run the connectivity logic in this case.
1. Improved logic in selectpeers.DIP6()
2. Updated tests
Run unit tests
None

fix(selectpeers): add fallback for less than 5 validators

---

CHANGELOG_PENDING.md
light/client.go
light/client_test.go
light/detector.go
light/provider/mock/deadmock.go
light/provider/mock/mock.go

Backport of the upstream commit "b69ac23fd20bdc00dea00c7c8a69fa66f2e675a9": add case to catch cancelled contexts within the detector
* manually backport the changes from upstream commit b69ac23fd20bdc00dea00c7c8a69fa66f2e675a9
* adapt an unit-test for an implementation of `tenderdash` light client
run unit-test locally
none

Backport the commit b69ac23fd20bdc00dea00c7c8a69fa66f2e675a9 from v.34.12

---

test/e2e/README.md

Describe how to keep validators public keys at full node
Update e2e documentation
nothing
nothing

docs(e2e): update e2e doc how to keep validators public keys at full node

---

types/validator_set.go
types/vote_set.go
types/vote_set_test.go

```
BUG: CONSENSUS FAILURE!!! - entering precommit wait step (12928/0), but precommits does not have any +2/3 votes
```
Some parts of the code were not correctly modified to support LLMQ quorums.
This PR fixes this behavior.
Added unit test, to be tested on schnapps once we have a pre-release
None

fix: panic on precommits does not have any +2/3 votes

---

consensus/mempool_test.go
consensus/state.go

Dash Drive needs additional (empty) block generated after AppHash change, so that we will have 2 blocks generated for each apphash change.
Modified needProofBlock to check apphash from block height-1 and height-2 when determining whether or not we should force new block creation. Note this feature needs empty block creation enabled:
* create_empty_blocks: true
* create_empty_blocks_interval > 0
* Manual test by running e2e tests and observing results
* TestMempoolNoProgressUntilTxsAvailable also tests if it works
none

feat(consensus): add empty block on h-1 and h-2 apphash change

---

dash/quorum/validator_conn_executor.go
dash/quorum/validator_conn_executor_test.go
node/node.go
p2p/switch.go
test/e2e/Makefile
test/e2e/networks/island.toml

if isolate every validator from each other and run e2e test, then we will see that the test fails 'cause no one validator could establish connection despite initial validator-set is provided in init-chain response. it happens due to `ValidatorConnExecutor` component doesn't establish a connection from `init-chain`.
Allow `ValidatorConnExecutor` using validator-set from init-chain response to establish connection with them
Using e2e test
None

feat: use validators from init chain response or genesis to establish connection

---

config/config.go
config/toml.go
consensus/mempool_test.go
consensus/state.go

Added `create_proof_block_range` configuration option to control the proof block creation algorithm.
1. Added `create_proof_block_range` with default value of `2`.
2. Updated `needProofBlock()` to reflect new configuration option.
With unit tests: 
`go test -test.v -test.run TestMempoolNoProgressUntilTxsAvailable ./consensus/ | grep needProofBlock `
none

feat(consensus): add create_proof_block_range config option

---

config/config.go

In #241 , we have created a feature and configuration option that allows us to control how many additional proof blocks are created in certain circumstances. In #243 , new configuration option was added to control this behavior, but it took a default of `2` instead of `1` which was in Tenderdash 0.6. 
In this PR, we restore original behavior by setting default value of this config option to 1.
Set default value of `create_proof_block_range` config option to `1`.
Github pipelines (Unit tests, e2e tests)
None

fix(consensus): create only 1 proof block by default

---

internal/consensus/peer_state.go
internal/consensus/types/peer_round_state.go
types/vote.go

When logging certain objects, zerolog is accessing its fields without proper locking, causing potential race conditions.
Implemented MarshalZerologObject method for several types that were affected:
* PeerState
* PeerRoundState
* Vote
Investigated output of unit tests
n/a

fix(consensus): race condition when logging

---

config/config.go
internal/blocksync/v0/reactor.go
internal/consensus/peer_state.go
internal/consensus/reactor.go
internal/consensus/state.go
internal/evidence/reactor.go
internal/mempool/v0/reactor.go
internal/mempool/v1/reactor.go
internal/p2p/pex/pex_reactor.go
internal/p2p/router.go
internal/p2p/transport_memory.go
internal/statesync/reactor.go
libs/log/default.go
types/block.go

Debug logs use huge amount of memory, causing some consensus tests to fail due to performance issues.
This PR fixes the biggest issues, and also significantly reduces amount of generated logs.
1. Decrease usage of `logger.With()` that take much memory and create new Log object
2. Added zerolog marshaller to Commit message, to allow more selective logging
3. Commented out `received message` and `sent message` debug logs to significantly decrease amount of generated logs
4. Removed redundant logs
5. Improved performance of key-value processing in logs
Ran consensus test that was failing: 
```
go test ./internal/consensus/ -test.timeout 60s -test.run TestReactorValidatorSetChanges  -memprofile memprofile.out -cpuprofile cpuprofile.out -count 1 -test.v 
```
none
**For repository code-owners …

fix(consensus): Decrease memory used by debug logs

---

dash/quorum/nodeid_resolver.go
dash/quorum/validator_conn_executor.go
go.mod
internal/p2p/dash_dialer.go
test/e2e/networks/rotate.toml
test/e2e/runner/setup.go
types/validator_address.go

Tcp NodeID resolver is stopped running ValidatorConnExecutor, if even one node is unavailable
Node ID resolve failures are not critical. We just skill nodes where we cannot determine node ID.
Using e2e test
none

fix(dash/quorum): tendermint stops when validator node id lookup fails

---

.github/workflows/lint.yml

After update, golangci-lint fails due to dependencies on cobra and viper. We don't support recent cobra/viper yet.
Revert golangci-lint-action to 2.5.2
Push and see if linter passes
None

build: fix golangci-lint

---

internal/consensus/reactor.go
internal/consensus/state.go

Noticed that there are several functions with identical bodies. This PR replaced those functions on one that covers all required logic.
Following functions
* `processStateCh`
* `processDataCh`
* `processVoteCh`
* `processVoteSetBitsCh`
were replaced with this function `processMsgCh`
Unit-test
N/A

refactor(consensus): replace message process handlers on a common one

---

internal/mempool/v0/clist_mempool.go
internal/mempool/v0/clist_mempool_test.go
internal/mempool/v1/mempool.go
types/tx.go

Test TestMempool_KeepInvalidTxsInCache didn't correctly check if KeepInvalidTxsInCache actually works.
Updated the test to ensure it really verifies if setting KeepInvalidTxsInCache to true/false works  correctly.
Run it.
None

test(mempool): fix test of KeepInvalidTxsInCache

---

Makefile

Fix linux-build task
Remove `GOARCH=amd64` option from linux build command
Build image locally
N/A

fix: remove option GOARCH=amd64 form linux build

---

.github/actions/bls/action.yml
.github/workflows/build.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
Makefile
docs/introduction/install.md

During backporting of 0.35.1, there were many changes introduced into github actions code that are conflicting with
Tenderdash-specific actions code.
Besides that, ARM builds don't correctly cross-compile with C libraries (CGO).
1. Moved bls code to separate github action (actions/bls/action.yml)
2. Refactored github workflows to simplify and remove repetition
3. Improved Makefile to support ARM cross-compilation on Ubuntu
4. Improved Makefile to make it possible to build only tenderdash, without building BLS
5. Updated docs
NOT done: 
1. BLS does not support building for ARM, so the ARM cross-compilation requires additional effort.
Run pipelines
n/a

refactor(ci): move bls CI code to a separate action and improve ARM build

---

internal/statesync/reactor.go
internal/statesync/reactor_test.go

Noticed that the unit-test `TestReactor_Backfill`
1. works unstable
2. takes time
In this PR, I tried to eliminate both mentioned issues
1. Made `sleep` and `request` timeouts configurable, to be able to use different values for the test
2. refactor `context` usage
unit-test
no

refactor: improve statesync.backfill

---

consensus/state.go
consensus/state_test.go
crypto/xchacha20poly1305/xchachapoly_test.go
p2p/conn/connection.go
types/block.go

Network got stuck due to outdated proposal block.
If the proposal block is older than time set in `proposed_block_time_window`, the network refuses to vote on it and votes NIL instead. This causes the network to freeze.
Visible result is that the network is frozen at some height, while creating new rounds over and over.
* check if the proposal block is expired, and regenerate it if needed
* added test to check this condition
* run unit tests
none

fix(consensus): network stuck due to outdated proposal block

---

scripts/release/cliff.toml
scripts/release/release.sh

release script did not generate changelog correctly, and didn't create a release.
* fixed changelog generation
* implemented creation of github releases inside the script
On tenderdash repo, drafted prerelease 0.8.0-dev.2:
* https://github.com/dashevo/tenderdash/pull/333
* https://github.com/dashevo/tenderdash/releases/tag/untagged-8f4c27d3a5dd012c6270
none

build(release): implement full release workflow in the release script

---

internal/consensus/peer_state.go
internal/consensus/reactor.go
internal/p2p/router.go

After some refactoring in `refactor/consensus-reactor-send-broadcast` branch. 
there was detected data-race between reading data from GO channel and closing it.
To solve the data-race issue in `p2p.Channel` was added an additional `select` block to check, were channel,  a peer, or a reactor close to stopping sending a message
Unit-test
No

fix: data-race when sending a message from consensus/reactor to a peer via p2p.Channel

---

scripts/release/release.sh

* chore(release): update changelog generation config
* build(release): improve version release script
* feat(release): release script now creates GitHub release
Backport #332
git cherry-pick  f6ff18f844c38165e0627eaecfe5d840b5c450e3
Will test during release
none

build(release): implement full release workflow in the release script (backport #332)

---

internal/consensus/invalid_test.go
internal/consensus/reactor.go
internal/state/execution.go

Detected data-race https://github.com/dashevo/tenderdash/runs/6110751227?check_suite_focus=true
```
WARNING: DATA RACE
Read at 0x00c000519bd0 by goroutine 85:
runtime.chansend()
/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/chan.go:158 +0x0
github.com/tendermint/tendermint/internal/consensus.invalidDoPrevoteFunc.func1()
/home/runner/work/tenderdash/tenderdash/internal/consensus/invalid_test.go:120 +0xe55
Previous write at 0x00c000519bd0 by goroutine 130:
runtime.closechan()
/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/chan.go:355 +0x0
github.com/tendermint/tendermint/internal/p2p.(*Channel).Close()
/home/runner/work/tenderdash/tenderdash/internal/p2p/router.go:120 +0x11b
github.com/tendermint/tendermint/internal/consensus.(*Reactor).processMsgCh·dwrap·52() …
```

fix: change a way of interacting with p2p channels in consensus reactor

---

third_party/bls-signatures/build.sh

**This is a clone #355 for `v0.8-dev` branch.**
* This fix is a result of reported issue #351 
* Since a release source code archive is not tracked by git, then to build a project we need support a way of obtaining bls-signature submodule
* Display a message about fallback scenario
* Clone "develop_0.1" single branch to be able to build a project
Build the project locally from archive
N/A

chore: clone bls library if tenderdash is not tracked by git for v0.8-dev branch

---

third_party/bls-signatures/build.sh

* This fix is a result of reported issue #351 
* Since a release source code archive is not tracked by git, then to build a project we need support a way of obtaining bls-signature submodule
if the tenderdash source code is not tracked by git then:
* Display a message about fallback scenario
* Clone "develop_0.1" single branch to be able to build a project
Build the project locally from archive
N/A

chore: clone bls library if tenderdash is not tracked by git

---

light/client.go

After backport v0.35.2 a test `TestClientHandlesContexts` became flaky
Removed select block to don't block sending a witness response.
_This bug came from upstream_
Running `TestClientHandlesContexts`
N/A

fix: remove select block to don't block sending a witness response

---

config/config.go
config/toml.go
dash/quorum/validator_conn_executor.go
internal/consensus/state.go
node/node.go
test/e2e/node/main.go
test/e2e/pkg/utils.go
test/e2e/runner/setup.go
types/priv_validator.go

Tenderdash didn't start in configuration where privval is implemented by Dash Core.
Also, some config options are misplaced.
1. Added support for `privval.DashCoreSignerClient`
2. Moved core priv validator settings to `[priv-validator]` section
3. Failure to execute ValidatorConnExecutor is not stopping startup of tenderdash anymore.

fix(consensus): unsupported priv validator type - dashcore.RPCClient

---

internal/rpc/core/mempool.go
rpc/coretypes/responses.go

@jawid-h reported about missed "info" field in a response on a `broadcast-tx--sync` request
Added `info` field to a response, data takes from a abci response
Test
N/A

fix: add a missed "info" field to broadcast-tx-response

---

CHANGELOG.md
scripts/release/cliff-pre.toml
scripts/release/release.sh

In the changelog, we want the following behavior:
1. For a prerelease, each prerelease should be listed with all changes
2. For a full release, all changes should be consolidated into the full release version (no prereleases in the changelog of full release)
1. Full changelog is regenerated with every release
2. History before 0.7.0  is dropped from the changelog
Locally
None

chore(release): hide prereleases in full release changelog

---

internal/state/state.go
internal/state/validation.go
rpc/client/evidence_test.go

The platform team found an issue, where if a block has a height of 1, then block time is taken from genesis
The behaviour when block time is used last-block-time from genesis doesn't exists in upstream and v0.9-dev. 
The same logic supported for v0.8-dev
Unit-Test / E2E
N/A

fix: don't use genesis last-block-time for a height is equal initial-height

---

config/config.go
internal/consensus/mempool_test.go

Drive team requested to add the ability to disable  proof block operation
Change validation 'create-proof-block-range', allow to set 0 to ignore proof block app hash
e2e tests
N/A

feat: allow `create-proof-block-range` to be `0`

---

spec/abci++/abci++_app_requirements_002_draft.md
spec/abci++/abci++_basic_concepts_002_draft.md
spec/abci++/abci++_methods_002_draft.md
spec/core/data_structures.md

chore: update abci++ spec

---

internal/consensus/replayer.go
internal/state/store.go

Some unit-tests were broken by refactoring kvstore, this PR is fixed its
Fix following tests:
* TestHandshakeInitialCoreLockHeight
* TestOneValidatorChangesSaveLoad
* TestManyValidatorChangesSaveLoad
Tests
N/A

fix: sbe unit tests

---

CHANGELOG.md
version/version.go

chore(release): update changelog and bump version to 0.10.0-dev.5

---

internal/consensus/byzantine_test.go
internal/consensus/common_test.go
internal/consensus/invalid_test.go
internal/consensus/reactor.go
internal/consensus/reactor_test.go
internal/consensus/replay_test.go
internal/consensus/state.go
internal/consensus/state_test.go

Some of the logic corresponding to the private-validator in `consensus.State` is redundant and cannot be used
This PR includes some changes of related to usage of private-validator in consensus.State.
1. Gather private-validator and its pro-tx-hash in one structure
2. Remove the field private-validator-type as a redundant
3. Remove redundant `updatePrivValidatorProTxHash` method, because pro-tx-hash can't be changed
4. Simplify `State.SetPrivValidator` method
Unit and E2E tests
N/A

refactor(consensus): optimize initialize priv-validator

---

internal/blocksync/pool.go
internal/blocksync/reactor_test.go

Even if during block sync operation a block was received then a routine still waits until a context will cancel
* Exit from `bpRequester.requestRoutine` if a block is received
* simplify logic `bpRequester.requestRoutine`
Unit/E2E tests
N/A

refactor: blocksync.bpRequester should stop procedure if block was received

---

internal/consensus/state.go
internal/consensus/types/height_vote_set.go
internal/consensus/types/height_vote_set_test.go

`peerID` is used as a key in `HeightVoteSet.peerCatchupRounds` map
Since, vote has `validatorProTxHash` field, then we can use this value instead of peerID
This improvement allows us to remove second argument (peerID) from `HeightVoteSet.AddVote` method, and rely only on data in the vote
1. Use `Vote.ValidatorProTxHash` in a `HeightVoteSet.peerCatchupRounds` map
2. Remove `peerID` form `HeightVoteSet.AddVote`
3. Fix `TestPeerCatchupRounds ` test
Unit / E2E tests
N/A

refactor: replace peerID on proTxHash in peer-catchup-rounds map

---

dash/core/client.go
dash/core/mock.go
internal/consensus/replayer.go
node/node.go
privval/dash_core_signer_client.go

To avoid to maintain 2 validation functions, need to replace custom implementation on using native LLMQType.Validate method
Replaced custom function `ValidateQuorumType` on to call `LLMQType.Validate()` method
Tests
N/A

refactor: use llmq.Validate function to validate llmq type

---

internal/p2p/peermanager.go
internal/p2p/pex/reactor_test.go

The tests in `pex` module are flaky, i.e. `TestReactorConnectFullNetwork`
```
go test ./internal/p2p/pex -test.run TestReactorConnectFullNetwork -race -test.v -test.count 10
=== RUN   TestReactorConnectFullNetwork
reactor_test.go:65: started ef59301921b33674348cc04ef4e63f8159bdb234
reactor_test.go:65: started 395bc84197103724210f39587cb11a597c631696
reactor_test.go:65: started 47c54b7311f120d81702f23b399761985df35fa4
reactor_test.go:65: started 436ed2bf9bac168ca7f403c5f78c66e7fabc94d3
--- PASS: TestReactorConnectFullNetwork (2.02s)
=== RUN   TestReactorConnectFullNetwork
reactor_test.go:65: started 21ac0dd98f38a817e15389961511803c164dfbb1
reactor_test.go:65: started afaff974a583bcb46237ff53a1fc9d8f423b33d4
reactor_test.go:65: started 37f264190bb20b4fb67c923f07f0818256262a87 …
```

fix: potential deadlock in pex module tests

---

internal/blocksync/reactor_test.go
internal/mempool/p2p_msg_handler.go
internal/mempool/p2p_msg_handler_test.go
internal/mempool/reactor.go
internal/mempool/reactor_test.go
internal/mempool/types.go
internal/p2p/channel_params.go
internal/p2p/client/chanstore.go
internal/p2p/client/client.go
internal/p2p/p2ptest/network.go
internal/p2p/pex/reactor_test.go
node/node.go
node/setup.go

This PR is a another part of the migration on using p2p-client for the modules which are used p2p layer for communication
* refactored `mempool` module to use p2p-client to gossip and handle mempool messages.
* moved MempoolChannel from `mempool` into `p2p` package
* refactored `p2ptest` package to support new `p2p-client` functionality. this slightly affected unit tests pf `blocksync` and `pex` modules.

refactor: introduce p2p client in mempool module

---

dash/llmq/llmq.go
types/validator_set.go

Some quorum types were missed in  `types.QuorumParams` 
Synced missed quorum parameters

fix: update quorum params

---

.github/workflows/markdown-linter.yml
dash/llmq/llmq.go
types/validator_set.go

v0.11-dev has some commits which we need to backport into v0.12-dev
Backported the latest commits from v0.11-dev into v0.12-dev
N/A
N/A

backport: catch up with the latest commits from v0.11 to v0.12

---

internal/consensus/block_executor.go
internal/consensus/event_publisher.go
internal/consensus/gossip_peer_worker.go
internal/consensus/gossiper.go
internal/consensus/msg_handlers.go
internal/consensus/peer_state.go
internal/consensus/proposal_updater.go
internal/consensus/reactor.go
internal/consensus/replay.go
internal/consensus/replayer.go
internal/consensus/round_scheduler.go
internal/consensus/state.go
internal/consensus/state_add_prop_block.go
internal/consensus/state_add_vote.go
internal/consensus/state_data.go
internal/consensus/state_enter_commit.go
internal/consensus/state_enter_new_round.go
internal/consensus/state_enter_precommit.go
internal/consensus/state_enter_prevote.go
internal/consensus/state_enter_propose.go
internal/consensus/state_enter_wait.go
internal/consensus/state_prevoter.go
internal/consensus/state_proposaler.go
internal/consensus/state_try_add_commit.go
internal/consensus/state_try_finalize_commit.go
internal/consensus/ticker.go
internal/consensus/vote_signer.go

Tenderdash generates too many logs in Debug level.
Modified log level for some commonly used logs:
1. Logs that show normal operation (primary execution path) of system are at Trace level
2. Important logs that add significant value are at Debug level
3. Logs that show error conditions are on Error level
4. Logs intended to the user (MNO/sysops) are Info or Error
Github Actions
None

chore(consensus): improve logs

---

internal/evidence/reactor.go
internal/p2p/router.go

Right now, evidence is sent to all peers, which is not necessary and can generate huge load during chain halt.
Reproduction scenario:
1. Stop majority of chain nodes (except one)
2. Remove WAL from stopped nodes
3. Break the code so that the chain will be halted
4. Start stopped nodes
As a result, these nodes will generate huge amount of evidence messages, which will be sent to all peers repeatedly. On big enough network, this will cause significant load.
We no longer repeatedly send evidence to all connected peers.
Instead:
1. When a peer connects, we send all evidence from the pool to it.
2. When new evidence arrives, we broadcast it to all peers.
TODO
None

fix(evidence): send evidence only once

---

internal/evidence/verify.go

```
{"level":"error","module":"evidence","err":"panic in processing message: runtime error: invalid memory address or nil pointer dereference","stack":"goroutine 139 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/internal/evidence.(*Reactor).handleMessage.func1()\n\tgithub.com/tendermint/tendermint/internal/evidence/reactor.go:143 +0x90\npanic({0x1072d00, 0x1d915a0})\n\truntime/panic.go:884 +0x20c\ngithub.com/tendermint/tendermint/internal/evidence.VerifyDuplicateVote(0x40093e9d80, {0x4001ebcc70, 0xf}, 0x400941fa40)\n\tgithub.com/tendermint/tendermint/internal/evidence/verify.go:137 +0x5b8\ngithub.com/tendermint/tendermint/internal/evidence.(*Pool).verify(0x4000154240, {0x15cd698, 0x4001ef4210}, {0x15d3378, …
```

fix: panic verifying evidence due to missing pubkey

---

cmd/tenderdash/commands/root.go
cmd/tenderdash/main.go
libs/log/default.go
libs/log/logger.go

log-file-path setting does not work
1. Fixed the bug by adding relevant logic to `log.OverrideWithNewLogger()`
2. Refactored a bit - moved code from main.rs to log/ and simplifying it
3. Fixed logger close logic (defer is not triggered when using os.Exit, so we call it explicitly).
locally, with `make build;./build/tenderdash start`
None

fix: log-file-path setting does not work

---

cmd/tenderdash/commands/root.go
cmd/tenderdash/main.go
libs/log/default.go
libs/log/logger.go

backport: log-file-path setting does not work (#691)

---

internal/state/execution.go
internal/state/validation.go

If the proposed app version didn't change we would be sending back 0 to Platform. This behavior is incorrect. We should always send back the proposed app version. Platform allows for version downgrades as well.

fix: always propose with current app version

---

CHANGELOG.md
Makefile
internal/state/execution.go
internal/state/validation.go
version/version.go

chore(release): update changelog and bump version to 0.13.3

---

.github/actions/bls/action.yml
.github/workflows/build.yml
.github/workflows/check-generated.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/tests.yml
DOCKER/Dockerfile
docs/tutorials/go-built-in.md
docs/tutorials/go.md
go.mod
test/e2e/docker/Dockerfile
test/fuzz/README.md

New golang was released, with some useful stuff like bytes.Clone()
Updated golang to 1.21
Updated golangci-lint to 1.55
Updated golangci-lint-action to 3.7.0
Github tests.
New version of golang required to build

build(deps): update golang to 1.21

---

.github/workflows/docker.yml

Build time of docker images for arm takes long time, effectively slowing development.
Added option to select platforms to use when starting Docker job manually
Built Docker image:
* amd: https://github.com/dashpay/tenderdash/actions/runs/7294117823
* amd and arm: 
None

build: manual docker image build platform selection

---

CHANGELOG.md
version/version.go

chore(release): update changelog and bump version to 0.14.0-dev.2

---

.github/workflows/docker.yml

Docker releases are only built for x86-64
Fixed to build for both x86-64 and arm
GHA for manual dispatch: https://github.com/dashpay/tenderdash/actions/runs/7741309780
For release, it needs to be merged first before we test.
None

build: fix docker platforms for releases

---

DOCKER/Dockerfile
DOCKER/docker-entrypoint.sh

To test gRPC, we need to be able to provide `abci` config option using Docker env variable
Added support for `ABCI` env var in Docker. If set, it will replace `abci` option in config.toml.
Tested in https://github.com/dashpay/rs-tenderdash-abci/pull/50 GHA, "grpc" test.
None

feat(Docker): env var ABCI changes abci option in config.toml

---

abci/example/kvstore/kvstore.go
abci/example/kvstore/kvstore_test.go
abci/example/kvstore/snapshots.go
abci/example/kvstore/state.go
abci/example/kvstore/state_test.go
abci/example/kvstore/tx.go
internal/statesync/reactor_test.go
test/e2e/generator/generate.go
test/e2e/networks/dashcore.toml
test/e2e/networks/rotate.toml
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go
test/e2e/tests/app_test.go
types/genesis.go
types/genesis_test.go
types/vote_extension.go

TestApp_TxTooBig fails in GHA pipelines due to long execution time.
It is caused by JSON serialization within example kvstore application, which consumes significant amount of time and memory.
1. Instead of running the test on each node one by one, broadcast txs to all nodes first, and then check results in separate loop.
2. Refactored kvstore to use streaming JSON serialization and deserialization when saving/restoring state.
3. Changed `GenesisDoc.AppState` to `[]byte`
4. Updated e2e to use new format of initial app state
5. In e2e dashcore and rotate networks, decreased block size and evidence size to consume less resources during test
GHA
Genesis doc AppState MUST be a base64-encoded bytes array, not JSON string.

fix!: e2e tests are flaky due to slow app state processing

---

internal/libs/clist/clist.go

Under load, Tenderdash slows down significantly due to expensive logic inside go-deadlock, used in clist object.
go-deadlock processes backtrace, with takes much resources.
go-deadlock not used in clist library
Tested during performance tests and tuning of Dash Drive.
None 

fix(libs): go-deadlock slows down clist

---

abci/client/client.go
abci/client/socket_client.go
abci/client/socket_client_test.go
internal/mempool/p2p_msg_handler.go
internal/p2p/client/client.go
internal/rpc/core/mempool.go

Some transactions, like CheckTx, should time out if not processed within some reasonable time period. 
This helps avoid system overload.
In ABCI Socket Client, added a context which is checked before sending message. If message was waiting too long in a queue and context expired, error is returned.
CheckTX in gRPC (*BroadcastTx) and p2p was limited to 1 second.
GHA + testing on devnet.
Some GRPC and P2P requests can return context canceled error.

feat(abciclient): support timeouts in abci calls

---

config/config.go
config/toml.go
internal/mempool/p2p_msg_handler.go
internal/mempool/p2p_msg_handler_test.go
internal/mempool/reactor.go
internal/rpc/core/mempool.go

In #749 , we introduced timeout for CheckTx operation and hardcoded it to 1 second. 
In this PR, we add option to define this timeout in config file.
Added `[mempool].timeout-check-tx` and `[rpc].timeout-broadcast-tx` to config file. Defaults to 0 what means "disabled" (no timeout).
Not tested yet :) 
None

feat(config): allow configuration of check TX timeout for rpc and p2p tx broadcast

---

config/config.go

Multiple fields in the consensus config file are marked as deprecated for quite a long time.
Removed deprecated fields:
* DeprecatedTimeoutPropose
* DeprecatedTimeoutProposeDelta
* DeprecatedTimeoutPrevote
* DeprecatedTimeoutPrevoteDelta
* DeprecatedTimeoutPrecommit
* DeprecatedTimeoutPrecommitDelta
* DeprecatedTimeoutCommit
* DeprecatedSkipTimeoutCommit
Github Actions
The following fields are removed from config:
* timeout-propose
* timeout-propose-delta
* timeout-prevote
* timeout-prevote-delta
* timeout-precommit
* timeout-precommit-delta
* timeout-commit
* skip-timeout-commit

refactor(config)!: remove deprecated timeouts from config

---

abci/client/client.go
abci/client/grpc_client_test.go
abci/client/routed_client_test.go

We were not sure if parallel processing of multiple messages inside abci grpc client works correctly.
Implemented unit test
Just run the test :)
None

test(abciclient): add parallel grpc execution test

---

internal/consensus/state.go
internal/consensus/vote_signer.go
internal/mempool/mempool.go
internal/mempool/reactor.go

Small refactor to reuse already implemented tmsync.Waker instead of chan.
Replaced `txsAvailable chan struct{}` with `tmsync.Waker`
GHA
None

refactor(mempool): use tmsync.Waker when txs are available

---

libs/log/testing.go
types/block.go
types/block_test.go
types/tx.go

When logging block (also occurs on INFO level), all full transactions that are part of this block are logged.
Only log short hashes of transactions for no more than 20 txs. Append "..." at the end if there are more than 20 txs.
Added unit test
None

fix(types): don't log all txs in block

---

internal/blocksync/synchronizer.go
internal/consensus/common_test.go
internal/consensus/msg_handlers.go
internal/consensus/pbts_test.go
internal/consensus/state.go
internal/consensus/state_data.go
internal/consensus/state_proposaler.go
internal/state/execution.go
types/block.go
types/params.go
types/proposal.go
types/proposal_test.go
types/validation.go

TestTooFarInTheFutureProposal does not test if the proposal is too much in future.
* refactored proposal processing in tests to allow setting proposal delivery using a middleware
* refactored proposal-based timestamp to get more precise error description when proposal is not timely, and assert for this error in tests
Run GHA tests
None

test(consensus): fix flaky TestTooFarInTheFutureProposal

---

internal/consensus/state_test.go

TestEmitNewValidBlockEventOnCommitWithoutBlock is flaky.
In the tested scenario, Tenderdash changes round step to Precommit, and then quickly advances to ApplyCommit step.
```
{"level":"debug","module":"consensus","module":"consensus","message":"updating state data step to Precommit on EnterPrecommitAction"}
{"level":"debug","module":"consensus","module":"consensus","commit_round":1,"new_height":1,"height":1,"round":1,"step":6,"message":"entering commit step"}
{"level":"debug","module":"consensus","module":"consensus","commit":"8E4B2F2E5D2E168704B334B47F2FE394F1674E181A79E79FDA50AC03AC08618D","proposal":"","message":"commit is for a block we do not know about; set ProposalBlock=nil"}
{"level":"debug","module":"consensus","module":"consensus","message":"updating state data step to …
```

test(consensus): fix flaky TestEmitNewValidBlockEventOnCommitWithoutBlock

---

internal/statesync/block_queue.go
internal/statesync/reactor.go
internal/statesync/reactor_test.go

TestReactor_Backfill is flaky. 
Due to some timing constraints, sometimes backfill goes as low as height 8, while it should end on height 10.
This is caused by failure testing logic effectively "delaying" some blocks at higher heights.
1. Added mechanism to reject blocks below 10 to the tests.
2. Small refactoring of backfill error handling
```bash
#!/bin/bash -ex
while true; do
go test -count 1 -timeout 60s ./internal/statesync/ -test.v -run TestReactor_Backfill 2>&1 | tee log.log
if grep -q FAIL log.log; then
echo "Test failed, stopping."
break
fi
echo "================ Test passed, running again ================"
done
```
None

 test(statesync): fix flaky TestReactor_Backfill 

---

abci/types/types.pb.go
internal/state/current_round_state.go
internal/state/execution.go
internal/state/state_test.go
proto/tendermint/abci/types.proto
spec/abci++/api.md

If no validators were provided in ValidatorSetUpdate, the request was ignored.
If no validators are provided in ValidatorSetUpdate, quorum hash and threshold public key are still updated in the validator set.
Documented ValidatorSetUpdate in abci proto definitions file.
Added unit test.
None

fix(state): handle ValidatorSetUpdate with no validator changes

---

config/config.go
config/config_test.go

On seeds, `[abci]` section is unused and should be ignored.
* ignore `[abci]` section on seed nodes
* report errors from multiple sections at one run
Added unit test
None

fix(config): ignore abci section on seeds

---

internal/consensus/replayer.go
internal/state/current_round_state.go
types/protobuf.go
types/validator_set.go
types/vote.go

Tenderdash requires validator set updates to contain public keys of all validators. 
However, this should not be required, as in some scenarios (like replay) these
pubkeys are not available.
Validators in validator set no longer require public key.
On testnet, when got the failure, with the following procedure:
```bash
dashmate config set --config testnet platform.drive.tenderdash.docker.image dashpay/tenderdash:fix-validator-update-without-pubkey
dashmate stop --platform
dashmate reset --platform
dashmate start --platform
```

fix(types): abci valset update abci does not need a public key on replay

---

abci/server/socket_server.go
internal/p2p/router.go
internal/statesync/reactor.go
libs/log/default.go
libs/log/logger.go
types/block.go

Some logs at Error level are logged even if this is not error condition.
It makes logs interpretation a bit harder.
Decreased verbosity of some logs.
Implemented `Warn` log level.
Described approach to logging in comments to Logger interface.
GHA
None

chore(log): add Warn log level and decrease verbosity of some logs

---

types/validation_test.go
types/validator_set.go

If commit is created with a different quorum than it's verified, we don't have clear enough error.
Return better error on quorum hash mismatch.
GHA

chore(types): detect quorum hash mismatch when verifying commit

---

internal/p2p/router.go

```
fatal error: concurrent map iteration and map write                                                                                                                                   │
010.57942s full01         |                                                                                                                                                                                       │
010.57944s full01         | goroutine 605 gp=0xc0000ff180 m=3 mp=0xc000069008 [running]:                                                                                                                          │
010.57945s full01         | runtime.fatal({0x1c34522?, 0xc0000b4c38?}) …
```

fix(router): router.chDesc concurrent map iteration and write in pqueue

---

.github/dependabot.yml

Dependabot targets its changes to the master branch, while in our workflow, it should be the default branch (like v1.1)
Fixed dependabot config, updated reviewers
Cannot be tested, to be tested after merge as it only applies when it's in the default branch.
None

build(dependabot): run dependabot on default branch, not master

---

DOCKER/docker-entrypoint.sh

```
"Error": "driver failed programming external connectivity on endpoint dashmate_devnet-molotov-drive_tenderdash-1 (4a531e194624e830ef487082276645b79a5d9c6b37e888bfdf10dbe55ac7b8fc): failed to bind port 10.0.50.116:36660/tcp: Error starting userland proxy: listen tcp4 10.0.50.116:36660: bind: address already in use",
```
Most probably it happening because we do not close all connections before we panic so when docker restart the container we still have some incoming on the interface
**This is a temporary workaround!** A proper solution should be a graceful shutdown of tenderdash networking on panic.
- Added 10 seconds of sleep if tenderdash exits with non-zero code.
None
None

fix: address already in use

---

dash/quorum/validator_conn_executor.go
internal/p2p/dash_dialer.go
node/node.go
node/node_test.go

There is a `ValidatorConnExecutor` service that ensures that each active validator is connected to at least some other validators that are members of the same quorum. 
Unfortunately, after some backports/refactorings, this service is not started correctly anymore.
* fixed start issue
* decreased log levels in ValidatorConnExecutor 
Start e2e tests and monitor logs
None

fix: active validators not always connected to each other

---

CHANGELOG.md
version/version.go

chore(release): update changelog and bump version to 1.1.0-dev.3

---

dash/quorum/validator_conn_executor.go
node/node.go

On a large network, validators might not reach quorum on genesis due to lack of direct connectivity between them.
There is ValidatorConnExecutor reactor implemented which should overcome this issue, but it is triggered during FinalizeBlock.
Trigger ValidatorConnExecutor logic during node startup.
Log inspection of e2e tests output.
None

fix: validators form islands on genesis

---

Makefile
scripts/release/release.sh

Users want our binaries to be signed
Release script now builds and signs released binaries
When releasing v1.1.0
None

build: add signed binaries to releases

---

internal/consensus/state.go
internal/consensus/state_test.go
internal/consensus/ticker.go

When initial genesis time is in the future, the proposal is never generated and node gets stuck.
Fixed bug - round was not propagated in EnterProposeEvent.
Run e2e tests
Added one unit test
None

fix(consensus): proposal not generated after waiting for last block time to pass

---

Makefile
scripts/release/release.sh

Build of dev release fails due to mixing of comma- and space-separated tags in the build command.
Introduced in #854 
Use space-separated tags in build command
GHA + local build
None

build: dev releases fails due to invalid tags

---

Makefile
docs/tools/docker-compose.md
spec/ivy-proofs/README.md
test/e2e/pkg/infra/docker/exec.go

e2e tests stopped working due to missing `docker-compose` command
replaced with `docker` command with `compose` argument.
Run GHA tests
None

build: e2e tests fail due to lack of docker-compose command

---

internal/consensus/state.go

Internal message queue has a size of 1000, which is not big enough for a network with 100 validators.
Increased to 20 000.
GHA + devnet testing
None

fix(consensus): msg queue is too small for mainnet

---

internal/consensus/state_add_prop_block.go
internal/consensus/state_prevoter.go
internal/p2p/conn/connection.go

Some logs are not clear enough or too verbose
Improved logs:
* removed overly verbose trace-level connection logs  that don't add any value
* added node_id to consensus logs, added peer to consensus proposal logs
GHA
None

chore: improve logs

---

internal/evidence/pool.go
internal/evidence/pool_test.go
internal/evidence/reactor.go
internal/evidence/verify.go
internal/evidence/verify_test.go

Nodes that are not active validators don't have access to public keys of validators, so they cannot verify signatures in evidence.
1. Non-validators don't verify signatures
2. Non-validators don't add evidence to evidence pool, to avoid adding fake evidence
GHA
None

fix: non-active validators can't verify evidence signatures

---

node/node.go

If Tenderdash crashes/restarts before mining first (genesis) block, it persists some initial state and reuses it after restart.
It means that any changes to the `genesis.json` file are not loaded on restart..
Discard persisted state when persisted height is 0.
e2e tests
None

fix(node): genesis.json not loaded on restart before genesis block is mined

---

config/config.go
config/config_test.go
types/node_key.go

When node_key.json contains valid json but is malformed, commands like `tenderdash show-node-id` fail with panic.
Added validation
Manually with `tenderdash show-node-id`, added unit test.
None

fix(config): panic when loading invalid node key file

---

go.mod
go.sum

go-deadlock is broken with go 1.23: https://github.com/sasha-s/go-deadlock/issues/34, what causes false positives.
Updated go-deadlock to v0.3.5
GHA
None

build(deps): go-deadlock to 0.3.5 to fix false positives

---

.github/dependabot.yml
.github/workflows/e2e.yml
.github/workflows/stale.yml
.github/workflows/tests.yml

With current maintenance level, we need more time to process PRs.
Increased stale timeout for PRs to 1 month.
Limit Dependabot PRs to 5.
Run tests whenever go.sum changes (most likely due to dependabot updates).

chore(github): tune stale and dependabot settings
